"""
Internal PV lookup tables for FMX and AMX.

Each dict maps the legacy descriptor name (from epx.db / epxAMX.db) to the
full EPICS PV string (beamline_designation + DB prefix + suffix).

This module is **private to mxbluesky.devices** — application code must
never import it directly.  It exists to:
  1. Provide a single source of truth during the migration from pvLookupDict.
  2. Enable coverage checks that verify every DB descriptor is reachable via
     the new ophyd device layer.
  3. Be dropped once the device layer is feature-complete.

PV string construction:
    beamline_designation ("XF:17ID") + DB_entry = full PV
    e.g. "XF:17ID" + "C-ES:FMX{Gon:1-Ax:GX}Mtr" = "XF:17IDC-ES:FMX{Gon:1-Ax:GX}Mtr"
"""

_BL = "XF:17ID"  # beamline_designation shared by both beamlines

# ---------------------------------------------------------------------------
# Helper: expand raw DB entries to full PV strings
# ---------------------------------------------------------------------------
def _expand(entries):
    """Turn a list of (descriptor, db_entry) pairs into {descriptor: full_pv}."""
    return {desc: _BL + entry for desc, entry in entries}


# ---------------------------------------------------------------------------
# FMX  (epx.db)
# ---------------------------------------------------------------------------
PV_MAPS = {
    "fmx": _expand([
        # --- real motors ---
        ("fineX",             "C-ES:FMX{Gon:1-Ax:Xf}Mtr"),
        ("fineY",             "C-ES:FMX{Gon:1-Ax:Yf}Mtr"),
        ("fineZ",             "C-ES:FMX{Gon:1-Ax:Zf}Mtr"),
        ("omega",             "C-ES:FMX{Gon:1-Ax:O}Mtr"),
        ("sampleX",           "C-ES:FMX{Gon:1-Ax:GX}Mtr"),
        ("sampleY",           "C-ES:FMX{Gon:1-Ax:PY}Mtr"),
        ("sampleZ",           "C-ES:FMX{Gon:1-Ax:PZ}Mtr"),
        ("detectorDist",      "C-ES:FMX{Det-Ax:Z}Mtr"),
        ("fastShutter",       "C-ES:FMX{Sht:1-Ax:R}Mtr"),
        ("dewarRot",          "C-ES:FMX{Dew:1-Ax:R}Mtr"),
        ("slit1XGap",         "A-OP:FMX{Slt:1-Ax:XGap}Mtr"),
        ("slit1YGap",         "A-OP:FMX{Slt:1-Ax:YGap}Mtr"),
        ("cryoXY",            "C-ES:FMX{CS:1-Ax:XY}Mtr"),
        # --- virtual motors ---
        ("wavelength",        "A-OP:FMX{Mono:DCM-Ax:W}Mtr"),
        ("energy",            "A-OP:FMX{Mono:DCM-Ax:E}Mtr"),
        # --- control PVs ---
        ("RIattenEnergySP",   "C-OP:FMX{Attn:RI}Energy-SP"),
        ("beamAvailable",     "-OP:FMX{BeamAvail}"),
        ("exposing",          "-OP:FMX{Exposing}"),
        ("mercuryEraseStart", "C-ES:FMX{Det:Mer}mca1.ERST"),
        ("mercurySpectrum",   "C-ES:FMX{Det:Mer}mca1.VAL"),
        ("mercuryReadStat",   "C-ES:FMX{Det:Mer}mca1.READ"),
        ("zoom2FrameRate",    "C-ES:FMX{Cam:7}MJPG1:ArrayRate_RBV"),
        ("zoom1FrameRate",    "C-ES:FMX{Cam:7}MJPG2:ArrayRate_RBV"),
        ("zoom4FrameRate",    "C-ES:FMX{Cam:8}MJPG1:ArrayRate_RBV"),
        ("zoom3FrameRate",    "C-ES:FMX{Cam:8}MJPG2:ArrayRate_RBV"),
        ("stillMode",         "C-ES:FMX{Stills}"),
        ("standardMode",      "C-ES:FMX{Standard}"),
        ("stillModeStatus",   "C-ES:FMX{Stills}-Stat"),
        ("detCoverRBV",       "C-ES:FMX{Det:FMX-Cover}Pos-Sts"),
        ("detCoverOpen",      "C-ES:FMX{Det:FMX-Cover}Cmd:Opn-Cmd"),
        ("annealIn",          "C-ES:FMX{Wago:1}AnnealerAir-Sel"),
        ("annealStatus",      "C-ES:FMX{Wago:1}AnnealerIn-Sts"),
        ("sampleProtect",     "C-ES:FMX{SPSEnable}"),
        ("warmupThresholdRBV","C-ES:FMX{CS8}WarmupThreshold_RBV"),
        ("warmupThreshold",   "C-ES:FMX{CS8}WarmupThreshold"),
        ("gripperClosed",     "C-ES:FMX{Wago:1}BimbaClosed-Sts"),
        ("gripperOpen",       "C-ES:FMX{Wago:1}BimbaOpen-Sts"),
        ("robotForceX",       "C-ES:FMX{FTS:1}ForceX-I"),
        ("robotForceY",       "C-ES:FMX{FTS:1}ForceY-I"),
        ("robotForceZ",       "C-ES:FMX{FTS:1}ForceZ-I"),
        ("robotFTSensorStat", "C-ES:FMX{FTS:1}Status-I"),
        ("eigerIOC_reboot",   "C-CT:FMX{IOC:DET01}:SysReset"),
        ("rebootGovernor",    "C-ES:FMX{Gov}Cmd:Kill-Cmd"),
        ("stopEiger",         "C-ES:FMX{Det:Eig16M}cam1:Acquire"),
        ("eigerStatMessage",  "C-ES:FMX{Det:Eig16M}cam1:StatusMessage_RBV"),
        ("RI_Atten_SP",       "C-OP:FMX{Attn:RI}Trans-SP"),
        ("RI_Atten_SET",      "C-OP:FMX{Attn:RI}Cmd:Set-Cmd.PROC"),
        ("CRL_VS_IN",         "C-OP:FMX{CRL:02}Cmd:In-Cmd"),
        ("CRL_VS_OUT",        "C-OP:FMX{CRL:02}Cmd:Out-Cmd"),
        ("CRL_V2A_IN",        "C-OP:FMX{CRL:04}Cmd:In-Cmd"),
        ("CRL_V2A_OUT",       "C-OP:FMX{CRL:04}Cmd:Out-Cmd"),
        ("CRL_V1A_IN",        "C-OP:FMX{CRL:08}Cmd:In-Cmd"),
        ("CRL_V1A_OUT",       "C-OP:FMX{CRL:08}Cmd:Out-Cmd"),
        ("CRL_V1B_IN",        "C-OP:FMX{CRL:06}Cmd:In-Cmd"),
        ("CRL_V1B_OUT",       "C-OP:FMX{CRL:06}Cmd:Out-Cmd"),
        ("CRL_H4A_IN",        "C-OP:FMX{CRL:03}Cmd:In-Cmd"),
        ("CRL_H4A_OUT",       "C-OP:FMX{CRL:03}Cmd:Out-Cmd"),
        ("CRL_H2A_IN",        "C-OP:FMX{CRL:05}Cmd:In-Cmd"),
        ("CRL_H2A_OUT",       "C-OP:FMX{CRL:05}Cmd:Out-Cmd"),
        ("CRL_H1A_IN",        "C-OP:FMX{CRL:07}Cmd:In-Cmd"),
        ("CRL_H1A_OUT",       "C-OP:FMX{CRL:07}Cmd:Out-Cmd"),
        ("CRL_H1B_IN",        "C-OP:FMX{CRL:09}Cmd:In-Cmd"),
        ("CRL_H1B_OUT",       "C-OP:FMX{CRL:09}Cmd:Out-Cmd"),
        ("robotXMountLowLim", "C-ES:FMX{Gov:Robot-St:SA}LLim:gx-Pos"),
        ("robotXMountHiLim",  "C-ES:FMX{Gov:Robot-St:SA}HLim:gx-Pos"),
        ("robotXMountPos",    "C-ES:FMX{Gov:Robot-Dev:gx}Pos:Mount-Pos"),
        ("robotXWorkPos",     "C-ES:FMX{Gov:Robot-Dev:gx}Pos:Work-Pos"),
        ("robotYMountPos",    "C-ES:FMX{Gov:Robot-Dev:gpy}Pos:Mount-Pos"),
        ("robotYWorkPos",     "C-ES:FMX{Gov:Robot-Dev:gpy}Pos:Work-Pos"),
        ("robotZMountPos",    "C-ES:FMX{Gov:Robot-Dev:gpz}Pos:Mount-Pos"),
        ("robotZWorkPos",     "C-ES:FMX{Gov:Robot-Dev:gpz}Pos:Work-Pos"),
        ("robotOmegaWorkPos", "C-ES:FMX{Gov:Robot-Dev:go}Pos:Work-Pos"),
        ("gonXHiLim",         "C-ES:FMX{Gon:1-Ax:GX}Mtr.HLM"),
        ("gonXLoLim",         "C-ES:FMX{Gon:1-Ax:GX}Mtr.LLM"),
        ("governorMessage",   "C-ES:FMX{Gov:Robot}Sts:Msg-Sts"),
        ("transmissionRBV",   "C-OP:FMX{Attn:BCU}Trans-I"),
        ("transmissionSet",   "C-OP:FMX{Attn:BCU}Trans-SP"),
        ("transmissionGo",    "C-OP:FMX{Attn:BCU}Cmd:Set-Cmd.PROC"),
        ("transmissionDone",  "C-OP:FMX{Attn:BCU}attenDone"),
        ("totalCurrentBCU",   "C-BI:FMX{BPM:4}SumAll:MeanValue_RBV"),
        ("syncPinY",          "C-ES:FMX{Gon:1-Ax:PY}Mtr.SYNC"),
        ("syncPinZ",          "C-ES:FMX{Gon:1-Ax:PZ}Mtr.SYNC"),
        ("sampleDetected",    "C-ES:FMX{Wago:1}SampleDetected1-Sts"),
        ("boostSelect",       "C-ES:FMX{Wago:1}Boost-Sel"),
        ("boostStatus",       "C-ES:FMX{Wago:1}Boost-Sts"),
        ("gripTemp",          "C-ES:FMX{Wago:1}GripperTemp-I"),
        ("homePinY",          "C-CT:FMX{SDC:04-Ax:5}StartHome"),
        ("homePinZ",          "C-CT:FMX{SDC:04-Ax:6}StartHome"),
        ("mcaRoiLo",          "C-ES:FMX{Det:Mer}mca1.R0LO"),
        ("mcaRoiHi",          "C-ES:FMX{Det:Mer}mca1.R0HI"),
        ("vectorBufferTime",  "C-ES:FMX{Gon:1-Vec}Val:BufferTime-SP"),
        ("fineXPoints",       "C-ES:FMX{Gon:1-Ax:Xf}Vec.A"),
        ("fineXAmp",          "C-ES:FMX{Gon:1-Ax:Xf}Vec.B"),
        ("fineXOffset",       "C-ES:FMX{Gon:1-Ax:Xf}Vec.C"),
        ("fineYPoints",       "C-ES:FMX{Gon:1-Ax:Yf}Vec.A"),
        ("fineYAmp",          "C-ES:FMX{Gon:1-Ax:Yf}Vec.B"),
        ("fineYOffset",       "C-ES:FMX{Gon:1-Ax:Yf}Vec.C"),
        ("fineZPoints",       "C-ES:FMX{Gon:1-Ax:Zf}Vec.A"),
        ("fineZAmp",          "C-ES:FMX{Gon:1-Ax:Zf}Vec.B"),
        ("fineZOffset",       "C-ES:FMX{Gon:1-Ax:Zf}Vec.C"),
        ("fineXSendWave",     "C-ES:FMX{Gon:1-Ax:Xf}Vec.PROC"),
        ("fineYSendWave",     "C-ES:FMX{Gon:1-Ax:Yf}Vec.PROC"),
        ("fineZSendWave",     "C-ES:FMX{Gon:1-Ax:Zf}Vec.PROC"),
        ("fineXVecGo",        "C-ES:FMX{Gon:1-Ax:Xf}VecGo.PROC"),
        ("fineYVecGo",        "C-ES:FMX{Gon:1-Ax:Yf}VecGo.PROC"),
        ("fineZVecGo",        "C-ES:FMX{Gon:1-Ax:Zf}VecGo.PROC"),
        ("PIcommands",        "C-CT:FMX{MC:21}Asyn.AOUT"),
        ("backLightVal",      "C-ES:FMX{BL:1}Ch1Value"),
        ("govRobotSeReach",   "C-ES:FMX{Gov:Robot-St:SE}Sts:Reach-Sts"),
        ("govRobotSaReach",   "C-ES:FMX{Gov:Robot-St:SA}Sts:Reach-Sts"),
        ("govRobotBlReach",   "C-ES:FMX{Gov:Robot-St:BL}Sts:Reach-Sts"),
        ("govRobotDaReach",   "C-ES:FMX{Gov:Robot-St:DA}Sts:Reach-Sts"),
        ("govHumanDetDist",   "C-ES:FMX{Gov:Human-Dev:dz}Pos:In-Pos"),
        ("govRobotDetDist",   "C-ES:FMX{Gov:Robot-Dev:dz}Pos:In-Pos"),
        ("govHumanDetDistOut","C-ES:FMX{Gov:Human-Dev:dz}Pos:Out-Pos"),
        ("govRobotDetDistOut","C-ES:FMX{Gov:Robot-Dev:dz}Pos:Out-Pos"),
        ("lowMagAcquire",     "C-ES:FMX{Cam:7}cam1:Acquire"),
        ("lowMagAcquireTime", "C-ES:FMX{Cam:7}cam1:AcquireTime"),
        ("lowMagGain",        "C-ES:FMX{Cam:7}cam1:Gain"),
        ("lowMagImMode",      "C-ES:FMX{Cam:7}cam1:ImageMode"),
        ("lowMagTrigMode",    "C-ES:FMX{Cam:7}cam1:TriggerMode"),
        ("lowMagNumImages",   "C-ES:FMX{Cam:7}cam1:NumImages"),
        ("lowMagJpegNumImages","C-ES:FMX{Cam:7}JPEG1:NumCapture"),
        ("lowMagJpegFileNumber","C-ES:FMX{Cam:7}JPEG1:FileNumber"),
        ("lowMagJpegCapture", "C-ES:FMX{Cam:7}JPEG1:Capture"),
        ("lowMagJpegFilePath","C-ES:FMX{Cam:7}JPEG1:FilePath"),
        ("lowMagJpegFileName","C-ES:FMX{Cam:7}JPEG1:FileName"),
        ("lowMagJpegEnableCallbacks","C-ES:FMX{Cam:7}JPEG1:EnableCallbacks"),
        ("lowMagDetStateRBV", "C-ES:FMX{Cam:7}cam1:DetectorState_RBV"),
        ("topViewAcquire",    "C-ES:FMX{Cam:11}cam1:Acquire"),
        ("topViewAcquireTime","C-ES:FMX{Cam:11}cam1:AcquireTime"),
        ("topViewDataType",   "C-ES:FMX{Cam:11}cam1:DataType"),
        ("topViewGain",       "C-ES:FMX{Cam:11}cam1:Gain"),
        ("topViewImMode",     "C-ES:FMX{Cam:11}cam1:ImageMode"),
        ("topViewTrigMode",   "C-ES:FMX{Cam:11}cam1:TriggerMode"),
        ("topViewNumImages",  "C-ES:FMX{Cam:11}cam1:NumImages"),
        ("topViewJpegNumImages","C-ES:FMX{Cam:11}JPEG1:NumCapture"),
        ("topViewJpegFileNumber","C-ES:FMX{Cam:11}JPEG1:FileNumber"),
        ("topViewJpegCapture","C-ES:FMX{Cam:11}JPEG1:Capture"),
        ("topViewJpegFilePath","C-ES:FMX{Cam:11}JPEG1:FilePath"),
        ("topViewJpegFileName","C-ES:FMX{Cam:11}JPEG1:FileName"),
        ("topViewJpegEnableCallbacks","C-ES:FMX{Cam:11}JPEG1:EnableCallbacks"),
        ("topViewWriteFile",  "C-ES:FMX{Cam:11}JPEG1:WriteFile"),
        ("topViewDetStateRBV","C-ES:FMX{Cam:11}cam1:DetectorState_RBV"),
        ("robotGovStatus",    "C-ES:FMX{Gov:Robot}Sts:Status-Sts"),
        ("humanGovStatus",    "C-ES:FMX{Gov:Human}Sts:Status-Sts"),
        ("humanGovGo",        "C-ES:FMX{Gov:Human}Cmd:Go-Cmd"),
        ("robotGovGo",        "C-ES:FMX{Gov:Robot}Cmd:Go-Cmd"),
        ("humanSeActive",     "C-ES:FMX{Gov:Human-St:SE}Sts:Active-Sts"),
        ("humanXfActive",     "C-ES:FMX{Gov:Human-St:XF}Sts:Active-Sts"),
        ("humanBlActive",     "C-ES:FMX{Gov:Human-St:BL}Sts:Active-Sts"),
        ("humanSaActive",     "C-ES:FMX{Gov:Human-St:SA}Sts:Active-Sts"),
        ("humanDaActive",     "C-ES:FMX{Gov:Human-St:DA}Sts:Active-Sts"),
        ("humanMActive",      "C-ES:FMX{Gov:Human-St:M}Sts:Active-Sts"),
        ("robotSeActive",     "C-ES:FMX{Gov:Robot-St:SE}Sts:Active-Sts"),
        ("robotXfActive",     "C-ES:FMX{Gov:Robot-St:XF}Sts:Active-Sts"),
        ("robotBlActive",     "C-ES:FMX{Gov:Robot-St:BL}Sts:Active-Sts"),
        ("robotSaActive",     "C-ES:FMX{Gov:Robot-St:SA}Sts:Active-Sts"),
        ("robotDaActive",     "C-ES:FMX{Gov:Robot-St:DA}Sts:Active-Sts"),
        ("robotDiActive",     "C-ES:FMX{Gov:Robot-St:DI}Sts:Active-Sts"),
        ("robotMActive",      "C-ES:FMX{Gov:Robot-St:M}Sts:Active-Sts"),
        ("robotGovConfig",    "C-ES:FMX{Gov}Config-Sel"),
        ("robotGovActive",    "C-ES:FMX{Gov}Active-Sel"),
        ("zebraTriggering",   "C-ES:FMX{Zeb:3}:AND1_INP1:STA"),
        ("zebraDownloading",  "C-ES:FMX{Zeb:3}:ARRAY_ACQ"),
        ("zebraDownloadCount","C-ES:FMX{Zeb:3}:PC_NUM_DOWN"),
        ("zebraDisarm",       "C-ES:FMX{Zeb:3}:PC_DISARM"),
        ("zebraPulseDelay",   "C-ES:FMX{Zeb:3}:PC_PULSE_DLY"),
        ("zebraEncX",         "C-ES:FMX{Zeb:3}:PC_ENC1"),
        ("zebraEncY",         "C-ES:FMX{Zeb:3}:PC_ENC2"),
        ("zebraEncZ",         "C-ES:FMX{Zeb:3}:PC_ENC3"),
        ("zebraEncOmega",     "C-ES:FMX{Zeb:3}:PC_ENC4"),
        ("zebraReset",        "C-ES:FMX{Zeb:3}:SYS_RESET.PROC"),
        ("zebraRebootIOC",    "C-CT:FMX{IOC:Zeb3}:SysReset"),
        ("zebraSentTriggerStatus","C-ES:FMX{Zeb:3}:AND1_INP1:STA"),
        ("zebraArmStatus",    "C-ES:FMX{Zeb:3}:PC_ARM_INP:STA"),
        ("zebraPulseStatus",  "C-ES:FMX{Zeb:3}:PC_PULSE_INP:STA"),
        ("zebraTriggerReturnStatus","C-ES:FMX{Zeb:3}:AND1_INP2:STA"),
        ("zebraM1SetPosProc", "C-ES:FMX{Zeb:3}:M1:SETPOS.PROC"),
        ("zebraM2SetPosProc", "C-ES:FMX{Zeb:3}:M2:SETPOS.PROC"),
        ("zebraM3SetPosProc", "C-ES:FMX{Zeb:3}:M3:SETPOS.PROC"),
        ("zebraM4SetPosProc", "C-ES:FMX{Zeb:3}:M4:SETPOS.PROC"),
        ("zebraPCBITCAP0",    "C-ES:FMX{Zeb:3}:PC_BIT_CAP:B0"),
        ("zebraPCBITCAP1",    "C-ES:FMX{Zeb:3}:PC_BIT_CAP:B1"),
        ("zebraPCBITCAP2",    "C-ES:FMX{Zeb:3}:PC_BIT_CAP:B2"),
        ("zebraPCBITCAP3",    "C-ES:FMX{Zeb:3}:PC_BIT_CAP:B3"),
        ("zebraEncoder",      "C-ES:FMX{Zeb:3}:PC_ENC"),
        ("zebraDirection",    "C-ES:FMX{Zeb:3}:PC_DIR"),
        ("zebraGateSelect",   "C-ES:FMX{Zeb:3}:PC_GATE_SEL"),
        ("zebraGateStart",    "C-ES:FMX{Zeb:3}:PC_GATE_START"),
        ("zebraGateWidth",    "C-ES:FMX{Zeb:3}:PC_GATE_WID"),
        ("zebraGateStep",     "C-ES:FMX{Zeb:3}:PC_GATE_STEP"),
        ("zebraGateNumGates", "C-ES:FMX{Zeb:3}:PC_GATE_NGATE"),
        ("zebraTTlSel",       "C-ES:FMX{Zeb:3}:OUT1_TTL"),
        ("zebraPulseTriggerSource","C-ES:FMX{Zeb:3}:PC_PULSE_SEL"),
        ("zebraPulseStart",   "C-ES:FMX{Zeb:3}:PC_PULSE_START"),
        ("zebraPulseStep",    "C-ES:FMX{Zeb:3}:PC_PULSE_STEP"),
        ("zebraPulseWidth",   "C-ES:FMX{Zeb:3}:PC_PULSE_WID"),
        ("zebraPulseMax",     "C-ES:FMX{Zeb:3}:PC_PULSE_MAX"),
        ("zebraArm",          "C-ES:FMX{Zeb:3}:PC_ARM"),
        ("zebraArmOut",       "C-ES:FMX{Zeb:3}:PC_ARM_OUT"),
        ("zebraArmTrigSource","C-ES:FMX{Zeb:3}:PC_ARM_SEL"),
        ("vectorHold",        "C-ES:FMX{Gon:1-Vec}Hold-Sel"),
        ("vectorExpose",      "C-ES:FMX{Gon:1-Vec}Expose-Sel"),
        ("vectorGo",          "C-ES:FMX{Gon:1-Vec}Cmd:Go-Cmd"),
        ("vectorProceed",     "C-ES:FMX{Gon:1-Vec}Cmd:Proceed-Cmd"),
        ("vectorAbort",       "C-ES:FMX{Gon:1-Vec}Cmd:Abort-Cmd"),
        ("photonShutterOpen", "A-PPS:FMX{PSh}Cmd:Opn-Cmd"),
        ("photonShutterClose","A-PPS:FMX{PSh}Cmd:Cls-Cmd"),
        ("fastShutterOpenPos","C-ES:FMX{Gon:1-Sht}Pos:Opn-I"),
        ("fastShutterClosePos","C-ES:FMX{Gon:1-Sht}Pos:Cls-I"),
        ("vectorStartX",      "C-ES:FMX{Gon:1-Vec}Pos:XStart-SP"),
        ("vectorStartY",      "C-ES:FMX{Gon:1-Vec}Pos:YStart-SP"),
        ("vectorStartZ",      "C-ES:FMX{Gon:1-Vec}Pos:ZStart-SP"),
        ("vectorEndX",        "C-ES:FMX{Gon:1-Vec}Pos:XEnd-SP"),
        ("vectorEndY",        "C-ES:FMX{Gon:1-Vec}Pos:YEnd-SP"),
        ("vectorEndZ",        "C-ES:FMX{Gon:1-Vec}Pos:ZEnd-SP"),
        ("vectorStartOmega",  "C-ES:FMX{Gon:1-Vec}Pos:OStart-SP"),
        ("vectorEndOmega",    "C-ES:FMX{Gon:1-Vec}Pos:OEnd-SP"),
        ("vectorSync",        "C-ES:FMX{Gon:1-Vec}Cmd:Sync-Cmd"),
        ("vectorframeExptime","C-ES:FMX{Gon:1-Vec}Val:Exposure-SP"),
        ("vectorNumFrames",   "C-ES:FMX{Gon:1-Vec}Val:NumSamples-SP"),
        ("VectorActive",      "C-ES:FMX{Gon:1-Vec}Sts:Running-Sts"),
        ("VectorState",       "C-ES:FMX{Gon:1-Vec}Sts:State-Sts"),
        ("Atten01-0",         "C-OP:FMX{Attn:01}Cmd:Out-Cmd"),
        ("Atten02-0",         "C-OP:FMX{Attn:02}Cmd:Out-Cmd"),
        ("Atten03-0",         "C-OP:FMX{Attn:03}Cmd:Out-Cmd"),
        ("Atten04-0",         "C-OP:FMX{Attn:04}Cmd:Out-Cmd"),
        ("Atten05-0",         "C-OP:FMX{Attn:05}Cmd:Out-Cmd"),
        ("Atten06-0",         "C-OP:FMX{Attn:06}Cmd:Out-Cmd"),
        ("Atten07-0",         "C-OP:FMX{Attn:07}Cmd:Out-Cmd"),
        ("Atten08-0",         "C-OP:FMX{Attn:08}Cmd:Out-Cmd"),
        ("Atten09-0",         "C-OP:FMX{Attn:09}Cmd:Out-Cmd"),
        ("Atten10-0",         "C-OP:FMX{Attn:10}Cmd:Out-Cmd"),
        ("Atten11-0",         "C-OP:FMX{Attn:11}Cmd:Out-Cmd"),
        ("Atten12-0",         "C-OP:FMX{Attn:12}Cmd:Out-Cmd"),
        ("Atten01-1",         "C-OP:FMX{Attn:01}Cmd:In-Cmd"),
        ("Atten02-1",         "C-OP:FMX{Attn:02}Cmd:In-Cmd"),
        ("Atten03-1",         "C-OP:FMX{Attn:03}Cmd:In-Cmd"),
        ("Atten04-1",         "C-OP:FMX{Attn:04}Cmd:In-Cmd"),
        ("Atten05-1",         "C-OP:FMX{Attn:05}Cmd:In-Cmd"),
        ("Atten06-1",         "C-OP:FMX{Attn:06}Cmd:In-Cmd"),
        ("Atten07-1",         "C-OP:FMX{Attn:07}Cmd:In-Cmd"),
        ("Atten08-1",         "C-OP:FMX{Attn:08}Cmd:In-Cmd"),
        ("Atten09-1",         "C-OP:FMX{Attn:09}Cmd:In-Cmd"),
        ("Atten10-1",         "C-OP:FMX{Attn:10}Cmd:In-Cmd"),
        ("Atten11-1",         "C-OP:FMX{Attn:11}Cmd:In-Cmd"),
        ("Atten12-1",         "C-OP:FMX{Attn:12}Cmd:In-Cmd"),
        ("image_X_scalePix",  "C-ES:FMX{ClkCtr}image_X_scale.B"),
        ("image_X_scaleMM",   "C-ES:FMX{ClkCtr}image_X_scale.C"),
        ("image_Y_scalePix",  "C-ES:FMX{ClkCtr}image_Y_scale.B"),
        ("image_Y_scaleMM",   "C-ES:FMX{ClkCtr}image_Y_scale.C"),
        ("image_X_centerPix", "C-ES:FMX{ClkCtr}image_X_center.A"),
        ("image_Y_centerPix", "C-ES:FMX{ClkCtr}image_Y_center.A"),
        ("C2C_TargetX",       "C-ES:FMX{ClkCtr}image_X_target.A"),
        ("C2C_TargetY",       "C-ES:FMX{ClkCtr}image_Y_target.A"),
        ("C2C_Omega",         "C-ES:FMX{ClkCtr}OmegaPos.A"),
        ("C2C_Go",            "C-ES:FMX{ClkCtr}click_center.PROC"),
        ("gonioDone",         "C-ES:FMX{ClkCtr}gonioDone"),
        ("beamCenterX",       "-ES:FMX{Misc-BeamCenter:X}Pos-I"),
        ("beamCenterY",       "-ES:FMX{Misc-BeamCenter:Y}Pos-I"),
        ("lowMagCursorX",     "-ES:FMX{Misc-AuxCursor2:X}Pos-SP"),
        ("lowMagCursorY",     "-ES:FMX{Misc-AuxCursor2:Y}Pos-SP"),
        ("highMagCursorX",    "-ES:FMX{Misc-AuxCursor3:X}Pos-SP"),
        ("highMagCursorY",    "-ES:FMX{Misc-AuxCursor3:Y}Pos-SP"),
        ("vectorDelay",       "-ES:FMX{Misc-Vector:Delay}Pos-SP"),
        ("flux",              "A-OP:FMX{Mono:DCM-flux}"),
        ("sampleFlux",        "A-OP:FMX{Mono:DCM-dflux-MA}"),
        ("lowMagZoomMinXRBV", "C-ES:FMX{Cam:7}ROI3:MinX_RBV"),
        ("lowMagZoomMinYRBV", "C-ES:FMX{Cam:7}ROI3:MinY_RBV"),
        ("lowMagZoomMinX",    "C-ES:FMX{Cam:7}ROI3:MinX"),
        ("lowMagZoomMinY",    "C-ES:FMX{Cam:7}ROI3:MinY"),
        ("lowMagMinX",        "C-ES:FMX{Cam:7}ROI2:MinX"),
        ("lowMagMinY",        "C-ES:FMX{Cam:7}ROI2:MinY"),
        ("lowMagZoomROISizeXRBV","C-ES:FMX{Cam:7}ROI3:SizeX_RBV"),
        ("lowMagZoomROISizeYRBV","C-ES:FMX{Cam:7}ROI3:SizeY_RBV"),
        ("lowMagROISizeXRBV", "C-ES:FMX{Cam:7}ROI2:SizeX_RBV"),
        ("lowMagROISizeYRBV", "C-ES:FMX{Cam:7}ROI2:SizeY_RBV"),
        ("highMagZoomROISizeXRBV","C-ES:FMX{Cam:8}ROI1:SizeX_RBV"),
        ("highMagZoomROISizeYRBV","C-ES:FMX{Cam:8}ROI1:SizeY_RBV"),
        ("highMagROISizeXRBV","C-ES:FMX{Cam:8}ROI2:SizeX_RBV"),
        ("highMagROISizeYRBV","C-ES:FMX{Cam:8}ROI2:SizeY_RBV"),
        ("lowMagZoomMaxSizeXRBV","C-ES:FMX{Cam:7}ROI3:MaxSizeX_RBV"),
        ("lowMagZoomMaxSizeYRBV","C-ES:FMX{Cam:7}ROI3:MaxSizeY_RBV"),
        ("lowMagMaxSizeXRBV", "C-ES:FMX{Cam:7}ROI2:MaxSizeX_RBV"),
        ("lowMagMaxSizeYRBV", "C-ES:FMX{Cam:7}ROI2:MaxSizeY_RBV"),
        ("highMagZoomMaxSizeXRBV","C-ES:FMX{Cam:8}ROI1:MaxSizeX_RBV"),
        ("highMagZoomMaxSizeYRBV","C-ES:FMX{Cam:8}ROI1:MaxSizeY_RBV"),
        ("highMagMaxSizeXRBV","C-ES:FMX{Cam:8}ROI2:MaxSizeX_RBV"),
        ("highMagMaxSizeYRBV","C-ES:FMX{Cam:8}ROI2:MaxSizeY_RBV"),
        ("lowMagZoomSizeXRBV","C-ES:FMX{Cam:7}ROI3:ArraySizeX_RBV"),
        ("lowMagZoomSizeYRBV","C-ES:FMX{Cam:7}ROI3:ArraySizeY_RBV"),
        ("lowMagZoomBinXRBV", "C-ES:FMX{Cam:7}ROI3:BinX_RBV"),
        ("lowMagZoomBinYRBV", "C-ES:FMX{Cam:7}ROI3:BinY_RBV"),
        ("lowMagMinXRBV",     "C-ES:FMX{Cam:7}ROI2:MinX_RBV"),
        ("lowMagMinYRBV",     "C-ES:FMX{Cam:7}ROI2:MinY_RBV"),
        ("lowMagSizeXRBV",    "C-ES:FMX{Cam:7}ROI2:ArraySizeX_RBV"),
        ("lowMagSizeYRBV",    "C-ES:FMX{Cam:7}ROI2:ArraySizeY_RBV"),
        ("lowMagBinXRBV",     "C-ES:FMX{Cam:7}ROI2:BinX_RBV"),
        ("lowMagBinYRBV",     "C-ES:FMX{Cam:7}ROI2:BinY_RBV"),
        ("highMagZoomMinXRBV","C-ES:FMX{Cam:8}ROI1:MinX_RBV"),
        ("highMagZoomMinYRBV","C-ES:FMX{Cam:8}ROI1:MinY_RBV"),
        ("highMagZoomMinX",   "C-ES:FMX{Cam:8}ROI1:MinX"),
        ("highMagZoomMinY",   "C-ES:FMX{Cam:8}ROI1:MinY"),
        ("highMagMinX",       "C-ES:FMX{Cam:8}ROI2:MinX"),
        ("highMagMinY",       "C-ES:FMX{Cam:8}ROI2:MinY"),
        ("highMagZoomSizeXRBV","C-ES:FMX{Cam:8}ROI1:ArraySizeX_RBV"),
        ("highMagZoomSizeYRBV","C-ES:FMX{Cam:8}ROI1:ArraySizeY_RBV"),
        ("highMagZoomBinXRBV","C-ES:FMX{Cam:8}ROI1:BinX_RBV"),
        ("highMagZoomBinYRBV","C-ES:FMX{Cam:8}ROI1:BinY_RBV"),
        ("highMagMinXRBV",    "C-ES:FMX{Cam:8}ROI2:MinX_RBV"),
        ("highMagMinYRBV",    "C-ES:FMX{Cam:8}ROI2:MinY_RBV"),
        ("highMagSizeXRBV",   "C-ES:FMX{Cam:8}ROI2:ArraySizeX_RBV"),
        ("highMagSizeYRBV",   "C-ES:FMX{Cam:8}ROI2:ArraySizeY_RBV"),
        ("highMagBinXRBV",    "C-ES:FMX{Cam:8}ROI2:BinX_RBV"),
        ("highMagBinYRBV",    "C-ES:FMX{Cam:8}ROI2:BinY_RBV"),
        ("detectorNy",        "C-ES:FMX{Det:Eig16M}cam1:ArraySizeY_RBV"),
        ("detectorDescription","C-ES:FMX{Det:Eig16M}cam1:Description_RBV"),
        ("detectorNx",        "C-ES:FMX{Det:Eig16M}cam1:ArraySizeX_RBV"),
        ("detectorROIMode",   "C-ES:FMX{Det:Eig16M}cam1:ROIMode"),
        ("detectorPhotonEnergyRBV","C-ES:FMX{Det:Eig16M}cam1:PhotonEnergy_RBV"),
        ("detectorPhotonEnergy","C-ES:FMX{Det:Eig16M}cam1:PhotonEnergy"),
        ("dewarPlatePos",     "C-ES:FMX{CS8}PlatePosition"),
    ]),

    # ---------------------------------------------------------------------------
    # AMX  (epxAMX.db)
    # ---------------------------------------------------------------------------
    "amx": _expand([
        # --- real motors ---
        ("omega",             "B-ES:AMX{Gon:1-Ax:O}Mtr"),
        ("sampleX",           "B-ES:AMX{Gon:1-Ax:GX}Mtr"),
        ("sampleY",           "B-ES:AMX{Gon:1-Ax:PY}Mtr"),
        ("sampleZ",           "B-ES:AMX{Gon:1-Ax:PZ}Mtr"),
        ("detectorDist",      "B-ES:AMX{Det-Ax:Z}Mtr"),
        ("fastShutter",       "B-ES:AMX{Sht:1-Ax:R}Mtr"),
        ("dewarRot",          "B-ES:AMX{Dew:1-Ax:R}Mtr"),
        ("cryoXY",            "B-ES:AMX{CS:1-Ax:XY}Mtr"),
        # --- virtual motors ---
        ("wavelength",        "A-OP:AMX{Mono:DCM-Ax:W}Mtr"),
        ("energy",            "A-OP:AMX{Mono:DCM-Ax:E}Mtr"),
        # --- control PVs ---
        ("beamAvailable",     "-OP:AMX{BeamAvail}"),
        ("exposing",          "-OP:AMX{Exposing}"),
        ("mercuryEraseStart", "B-ES:AMX{Det:Mer}mca1.ERST"),
        ("mercurySpectrum",   "B-ES:AMX{Det:Mer}mca1.VAL"),
        ("mercuryReadStat",   "B-ES:AMX{Det:Mer}mca1.READ"),
        ("zoom2FrameRate",    "B-ES:AMX{Cam:6}MJPG1:ArrayRate_RBV"),
        ("zoom1FrameRate",    "B-ES:AMX{Cam:6}MJPG2:ArrayRate_RBV"),
        ("zoom3FrameRate",    "B-ES:AMX{Cam:7}MJPG2:ArrayRate_RBV"),
        ("zoom4FrameRate",    "B-ES:AMX{Cam:7}MJPG1:ArrayRate_RBV"),
        ("stillMode",         "B-ES:AMX{Stills}"),
        ("standardMode",      "B-ES:AMX{Standard}"),
        ("stillModeStatus",   "B-ES:AMX{Stills}-Stat"),
        ("detCoverRBV",       "B-ES:AMX{Det:AMX-Cover}Pos-Sts"),
        ("detCoverOpen",      "B-ES:AMX{Det:AMX-Cover}Cmd:Opn-Cmd"),
        ("annealIn",          "B-ES:AMX{Wago:1}AnnealerAir-Sel"),
        ("annealStatus",      "B-ES:AMX{Wago:1}AnnealerIn-Sts"),
        ("warmupThresholdRBV","B-ES:AMX{CS8}WarmupThreshold_RBV"),
        ("warmupThreshold",   "B-ES:AMX{CS8}WarmupThreshold"),
        ("gripperClosed",     "B-ES:AMX{Wago:1}BimbaClosed-Sts"),
        ("gripperOpen",       "B-ES:AMX{Wago:1}BimbaOpen-Sts"),
        ("robotForceX",       "B-ES:AMX{FTS:1}ForceX-I"),
        ("robotForceY",       "B-ES:AMX{FTS:1}ForceY-I"),
        ("robotForceZ",       "B-ES:AMX{FTS:1}ForceZ-I"),
        ("robotFTSensorStat", "B-ES:AMX{FTS:1}Status-I"),
        ("rebootGovernor",    "B-ES:AMX{Gov}Cmd:Kill-Cmd"),
        ("eigerIOC_reboot",   "B-CT:AMX{IOC:DET02}:SysReset.VAL"),
        ("stopEiger",         "B-ES:AMX{Det:Eig9M}cam1:Acquire"),
        ("eigerStatMessage",  "B-ES:AMX{Det:Eig9M}cam1:StatusMessage_RBV"),
        ("robotXMountLowLim", "B-ES:AMX{Gov:Robot-St:SA}LLim:gx-Pos"),
        ("robotXMountHiLim",  "B-ES:AMX{Gov:Robot-St:SA}HLim:gx-Pos"),
        ("robotXMountPos",    "B-ES:AMX{Gov:Robot-Dev:gx}Pos:Mount-Pos"),
        ("robotXWorkPos",     "B-ES:AMX{Gov:Robot-Dev:gx}Pos:Work-Pos"),
        ("robotYMountPos",    "B-ES:AMX{Gov:Robot-Dev:gpy}Pos:Mount-Pos"),
        ("robotYWorkPos",     "B-ES:AMX{Gov:Robot-Dev:gpy}Pos:Work-Pos"),
        ("robotZMountPos",    "B-ES:AMX{Gov:Robot-Dev:gpz}Pos:Mount-Pos"),
        ("robotZWorkPos",     "B-ES:AMX{Gov:Robot-Dev:gpz}Pos:Work-Pos"),
        ("robotOmegaWorkPos", "B-ES:AMX{Gov:Robot-Dev:go}Pos:Work-Pos"),
        ("gonXHiLim",         "B-ES:AMX{Gon:1-Ax:GX}Mtr.HLM"),
        ("gonXLoLim",         "B-ES:AMX{Gon:1-Ax:GX}Mtr.LLM"),
        ("governorMessage",   "B-ES:AMX{Gov:Robot}Sts:Msg-Sts"),
        ("sampleLifetime",    "A-OP:AMX{Mono:DCM-life}"),
        ("transmissionRBV",   "B-OP:AMX{Attn:BCU}Trans-I"),
        ("transmissionSet",   "B-OP:AMX{Attn:BCU}Trans-SP"),
        ("transmissionGo",    "B-OP:AMX{Attn:BCU}Cmd:Set-Cmd.PROC"),
        ("transmissionDone",  "B-OP:AMX{Attn:BCU}attenDone"),
        ("totalCurrentBCU",   "B-BI:AMX{BPM:3}SumAll:MeanValue_RBV"),
        ("syncPinY",          "B-ES:AMX{Gon:1-Ax:PY}Mtr.SYNC"),
        ("syncPinZ",          "B-ES:AMX{Gon:1-Ax:PZ}Mtr.SYNC"),
        ("sampleDetected",    "B-ES:AMX{Wago:1}SampleDetected1-Sts"),
        ("boostSelect",       "B-ES:AMX{Wago:1}Boost-Sel"),
        ("boostStatus",       "B-ES:AMX{Wago:1}Boost-Sts"),
        ("gripTemp",          "B-ES:AMX{Wago:1}GripperTemp-I"),
        ("homePinY",          "B-CT:AMX{SDC:04-Ax:5}StartHome"),
        ("homePinZ",          "B-CT:AMX{SDC:04-Ax:6}StartHome"),
        ("mcaRoiLo",          "B-ES:AMX{Det:Mer}mca1.R0LO"),
        ("mcaRoiHi",          "B-ES:AMX{Det:Mer}mca1.R0HI"),
        ("vectorBufferTime",  "B-ES:AMX{Gon:1-Vec}Val:BufferTime-SP"),
        ("backLightVal",      "B-ES:AMX{BL:1}Ch1Value"),
        ("govRobotSeReach",   "B-ES:AMX{Gov:Robot-St:SE}Sts:Reach-Sts"),
        ("govRobotSaReach",   "B-ES:AMX{Gov:Robot-St:SA}Sts:Reach-Sts"),
        ("govRobotBlReach",   "B-ES:AMX{Gov:Robot-St:BL}Sts:Reach-Sts"),
        ("govRobotDaReach",   "B-ES:AMX{Gov:Robot-St:DA}Sts:Reach-Sts"),
        ("govRobotDetDist",   "B-ES:AMX{Gov:Robot-Dev:dz}Pos:In-Pos"),
        ("govHumanDetDist",   "B-ES:AMX{Gov:Human-Dev:dz}Pos:In-Pos"),
        ("govRobotDetDistOut","B-ES:AMX{Gov:Robot-Dev:dz}Pos:Out-Pos"),
        ("govHumanDetDistOut","B-ES:AMX{Gov:Human-Dev:dz}Pos:Out-Pos"),
        ("lowMagAcquire",     "B-ES:AMX{Cam:6}cam1:Acquire"),
        ("lowMagAcquireTime", "B-ES:AMX{Cam:6}cam1:AcquireTime"),
        ("lowMagGain",        "B-ES:AMX{Cam:6}cam1:Gain"),
        ("lowMagImMode",      "B-ES:AMX{Cam:6}cam1:ImageMode"),
        ("lowMagTrigMode",    "B-ES:AMX{Cam:6}cam1:TriggerMode"),
        ("lowMagNumImages",   "B-ES:AMX{Cam:6}cam1:NumImages"),
        ("lowMagJpegNumImages","B-ES:AMX{Cam:6}JPEG1:NumCapture"),
        ("lowMagJpegFileNumber","B-ES:AMX{Cam:6}JPEG1:FileNumber"),
        ("lowMagJpegCapture", "B-ES:AMX{Cam:6}JPEG1:Capture"),
        ("lowMagJpegFilePath","B-ES:AMX{Cam:6}JPEG1:FilePath"),
        ("lowMagJpegFileName","B-ES:AMX{Cam:6}JPEG1:FileName"),
        ("lowMagJpegEnableCallbacks","B-ES:AMX{Cam:6}JPEG1:EnableCallbacks"),
        ("lowMagDetStateRBV", "B-ES:AMX{Cam:6}cam1:DetectorState_RBV"),
        ("topViewAcquire",    "B-ES:AMX{Cam:9}cam1:Acquire"),
        ("topViewAcquireTime","B-ES:AMX{Cam:9}cam1:AcquireTime"),
        ("topViewDataType",   "B-ES:AMX{Cam:9}cam1:DataType"),
        ("topViewGain",       "B-ES:AMX{Cam:9}cam1:Gain"),
        ("topViewImMode",     "B-ES:AMX{Cam:9}cam1:ImageMode"),
        ("topViewTrigMode",   "B-ES:AMX{Cam:9}cam1:TriggerMode"),
        ("topViewNumImages",  "B-ES:AMX{Cam:9}cam1:NumImages"),
        ("topViewJpegNumImages","B-ES:AMX{Cam:9}JPEG1:NumCapture"),
        ("topViewJpegFileNumber","B-ES:AMX{Cam:9}JPEG1:FileNumber"),
        ("topViewJpegCapture","B-ES:AMX{Cam:9}JPEG1:Capture"),
        ("topViewJpegFilePath","B-ES:AMX{Cam:9}JPEG1:FilePath"),
        ("topViewJpegFileName","B-ES:AMX{Cam:9}JPEG1:FileName"),
        ("topViewJpegEnableCallbacks","B-ES:AMX{Cam:9}JPEG1:EnableCallbacks"),
        ("topViewWriteFile",  "B-ES:AMX{Cam:9}JPEG1:WriteFile"),
        ("topViewDetStateRBV","B-ES:AMX{Cam:9}cam1:DetectorState_RBV"),
        ("robotGovStatus",    "B-ES:AMX{Gov:Robot}Sts:Status-Sts"),
        ("humanGovStatus",    "B-ES:AMX{Gov:Human}Sts:Status-Sts"),
        ("humanGovGo",        "B-ES:AMX{Gov:Human}Cmd:Go-Cmd"),
        ("robotGovGo",        "B-ES:AMX{Gov:Robot}Cmd:Go-Cmd"),
        ("humanSeActive",     "B-ES:AMX{Gov:Human-St:SE}Sts:Active-Sts"),
        ("humanXfActive",     "B-ES:AMX{Gov:Human-St:XF}Sts:Active-Sts"),
        ("humanBlActive",     "B-ES:AMX{Gov:Human-St:BL}Sts:Active-Sts"),
        ("humanSaActive",     "B-ES:AMX{Gov:Human-St:SA}Sts:Active-Sts"),
        ("humanDaActive",     "B-ES:AMX{Gov:Human-St:DA}Sts:Active-Sts"),
        ("humanMActive",      "B-ES:AMX{Gov:Human-St:M}Sts:Active-Sts"),
        ("robotSeActive",     "B-ES:AMX{Gov:Robot-St:SE}Sts:Active-Sts"),
        ("robotXfActive",     "B-ES:AMX{Gov:Robot-St:XF}Sts:Active-Sts"),
        ("robotBlActive",     "B-ES:AMX{Gov:Robot-St:BL}Sts:Active-Sts"),
        ("robotSaActive",     "B-ES:AMX{Gov:Robot-St:SA}Sts:Active-Sts"),
        ("robotDaActive",     "B-ES:AMX{Gov:Robot-St:DA}Sts:Active-Sts"),
        ("robotDiActive",     "B-ES:AMX{Gov:Robot-St:DI}Sts:Active-Sts"),
        ("robotMActive",      "B-ES:AMX{Gov:Robot-St:M}Sts:Active-Sts"),
        ("robotGovActive",    "B-ES:AMX{Gov}Active-Sel"),
        ("robotGovConfig",    "B-ES:AMX{Gov}Config-Sel"),
        ("zebraDownloading",  "B-ES:AMX{Zeb:2}:ARRAY_ACQ"),
        ("zebraDownloadCount","B-ES:AMX{Zeb:2}:PC_NUM_DOWN"),
        ("zebraDisarm",       "B-ES:AMX{Zeb:2}:PC_DISARM"),
        ("zebraEncX",         "B-ES:AMX{Zeb:2}:PC_ENC1"),
        ("zebraEncY",         "B-ES:AMX{Zeb:2}:PC_ENC2"),
        ("zebraEncZ",         "B-ES:AMX{Zeb:2}:PC_ENC3"),
        ("zebraEncOmega",     "B-ES:AMX{Zeb:2}:PC_ENC4"),
        ("zebraReset",        "B-ES:AMX{Zeb:2}:SYS_RESET.PROC"),
        ("zebraRebootIOC",    "B-CT:AMX{IOC:Zeb2}:SysReset"),
        ("zebraSentTriggerStatus","B-ES:AMX{Zeb:2}:AND1_INP1:STA"),
        ("zebraArmStatus",    "B-ES:AMX{Zeb:2}:PC_ARM_INP:STA"),
        ("zebraPulseStatus",  "B-ES:AMX{Zeb:2}:PC_PULSE_INP:STA"),
        ("zebraTriggerReturnStatus","B-ES:AMX{Zeb:2}:AND1_INP2:STA"),
        ("zebraM1SetPosProc", "B-ES:AMX{Zeb:2}:M1:SETPOS.PROC"),
        ("zebraM2SetPosProc", "B-ES:AMX{Zeb:2}:M2:SETPOS.PROC"),
        ("zebraM3SetPosProc", "B-ES:AMX{Zeb:2}:M3:SETPOS.PROC"),
        ("zebraM4SetPosProc", "B-ES:AMX{Zeb:2}:M4:SETPOS.PROC"),
        ("zebraPCBITCAP0",    "B-ES:AMX{Zeb:2}:PC_BIT_CAP:B0"),
        ("zebraPCBITCAP1",    "B-ES:AMX{Zeb:2}:PC_BIT_CAP:B1"),
        ("zebraPCBITCAP2",    "B-ES:AMX{Zeb:2}:PC_BIT_CAP:B2"),
        ("zebraPCBITCAP3",    "B-ES:AMX{Zeb:2}:PC_BIT_CAP:B3"),
        ("zebraEncoder",      "B-ES:AMX{Zeb:2}:PC_ENC"),
        ("zebraDirection",    "B-ES:AMX{Zeb:2}:PC_DIR"),
        ("zebraGateSelect",   "B-ES:AMX{Zeb:2}:PC_GATE_SEL"),
        ("zebraGateStart",    "B-ES:AMX{Zeb:2}:PC_GATE_START"),
        ("zebraGateWidth",    "B-ES:AMX{Zeb:2}:PC_GATE_WID"),
        ("zebraGateStep",     "B-ES:AMX{Zeb:2}:PC_GATE_STEP"),
        ("zebraGateNumGates", "B-ES:AMX{Zeb:2}:PC_GATE_NGATE"),
        ("zebraTTlSel",       "B-ES:AMX{Zeb:2}:OUT1_TTL"),
        ("zebraPulseTriggerSource","B-ES:AMX{Zeb:2}:PC_PULSE_SEL"),
        ("zebraPulseStart",   "B-ES:AMX{Zeb:2}:PC_PULSE_START"),
        ("zebraPulseStep",    "B-ES:AMX{Zeb:2}:PC_PULSE_STEP"),
        ("zebraPulseDelay",   "B-ES:AMX{Zeb:2}:PC_PULSE_DLY"),
        ("zebraPulseWidth",   "B-ES:AMX{Zeb:2}:PC_PULSE_WID"),
        ("zebraPulseMax",     "B-ES:AMX{Zeb:2}:PC_PULSE_MAX"),
        ("zebraArm",          "B-ES:AMX{Zeb:2}:PC_ARM"),
        ("zebraArmOut",       "B-ES:AMX{Zeb:2}:PC_ARM_OUT"),
        ("zebraArmTrigSource","B-ES:AMX{Zeb:2}:PC_ARM_SEL"),
        ("vectorHold",        "B-ES:AMX{Gon:1-Vec}Hold-Sel"),
        ("vectorExpose",      "B-ES:AMX{Gon:1-Vec}Expose-Sel"),
        ("vectorGo",          "B-ES:AMX{Gon:1-Vec}Cmd:Go-Cmd"),
        ("vectorProceed",     "B-ES:AMX{Gon:1-Vec}Cmd:Proceed-Cmd"),
        ("vectorAbort",       "B-ES:AMX{Gon:1-Vec}Cmd:Abort-Cmd"),
        ("vectorSync",        "B-ES:AMX{Gon:1-Vec}Cmd:Sync-Cmd"),
        ("photonShutterOpen", "A-PPS:AMX{PSh}Cmd:Opn-Cmd"),
        ("photonShutterClose","A-PPS:AMX{PSh}Cmd:Cls-Cmd"),
        ("fastShutterOpenPos","B-ES:AMX{Gon:1-Sht}Pos:Opn-I"),
        ("fastShutterClosePos","B-ES:AMX{Gon:1-Sht}Pos:Cls-I"),
        ("vectorStartX",      "B-ES:AMX{Gon:1-Vec}Pos:XStart-SP"),
        ("vectorStartY",      "B-ES:AMX{Gon:1-Vec}Pos:YStart-SP"),
        ("vectorStartZ",      "B-ES:AMX{Gon:1-Vec}Pos:ZStart-SP"),
        ("vectorEndX",        "B-ES:AMX{Gon:1-Vec}Pos:XEnd-SP"),
        ("vectorEndY",        "B-ES:AMX{Gon:1-Vec}Pos:YEnd-SP"),
        ("vectorEndZ",        "B-ES:AMX{Gon:1-Vec}Pos:ZEnd-SP"),
        ("vectorStartOmega",  "B-ES:AMX{Gon:1-Vec}Pos:OStart-SP"),
        ("vectorEndOmega",    "B-ES:AMX{Gon:1-Vec}Pos:OEnd-SP"),
        ("vectorframeExptime","B-ES:AMX{Gon:1-Vec}Val:Exposure-SP"),
        ("vectorNumFrames",   "B-ES:AMX{Gon:1-Vec}Val:NumSamples-SP"),
        ("VectorActive",      "B-ES:AMX{Gon:1-Vec}Sts:Running-Sts"),
        ("VectorState",       "B-ES:AMX{Gon:1-Vec}Sts:State-Sts"),
        ("image_X_scalePix",  "B-ES:AMX{ClkCtr}image_X_scale.B"),
        ("image_X_scaleMM",   "B-ES:AMX{ClkCtr}image_X_scale.C"),
        ("image_Y_scalePix",  "B-ES:AMX{ClkCtr}image_Y_scale.B"),
        ("image_Y_scaleMM",   "B-ES:AMX{ClkCtr}image_Y_scale.C"),
        ("image_X_centerPix", "B-ES:AMX{ClkCtr}image_X_center.A"),
        ("image_Y_centerPix", "B-ES:AMX{ClkCtr}image_Y_center.A"),
        ("C2C_TargetX",       "B-ES:AMX{ClkCtr}image_X_target.A"),
        ("C2C_TargetY",       "B-ES:AMX{ClkCtr}image_Y_target.A"),
        ("C2C_Omega",         "B-ES:AMX{ClkCtr}OmegaPos.A"),
        ("C2C_Go",            "B-ES:AMX{ClkCtr}click_center.PROC"),
        ("gonioDone",         "B-ES:AMX{ClkCtr}gonioDone"),
        ("lowMagCursorX",     "-ES:AMX{Misc-AuxCursor2:X}Pos-SP"),
        ("lowMagCursorY",     "-ES:AMX{Misc-AuxCursor2:Y}Pos-SP"),
        ("highMagCursorX",    "-ES:AMX{Misc-AuxCursor3:X}Pos-SP"),
        ("highMagCursorY",    "-ES:AMX{Misc-AuxCursor3:Y}Pos-SP"),
        ("beamCenterX",       "-ES:AMX{Misc-BeamCenter:X}Pos-I"),
        ("beamCenterY",       "-ES:AMX{Misc-BeamCenter:Y}Pos-I"),
        ("vectorDelay",       "-ES:AMX{Misc-Vector:Delay}Pos-SP"),
        ("flux",              "-ES:AMX{Misc-BeamFlux}Pos-SP"),
        ("sampleFlux",        "A-OP:AMX{Mono:DCM-dflux-MA}"),
        ("lowMagZoomMinXRBV", "B-ES:AMX{Cam:6}ROI1:MinX_RBV"),
        ("lowMagZoomMinYRBV", "B-ES:AMX{Cam:6}ROI1:MinY_RBV"),
        ("lowMagMinX",        "B-ES:AMX{Cam:6}ROI2:MinX"),
        ("lowMagMinY",        "B-ES:AMX{Cam:6}ROI2:MinY"),
        ("lowMagZoomMinX",    "B-ES:AMX{Cam:6}ROI1:MinX"),
        ("lowMagZoomMinY",    "B-ES:AMX{Cam:6}ROI1:MinY"),
        ("lowMagZoomROISizeXRBV","B-ES:AMX{Cam:6}ROI1:SizeX_RBV"),
        ("lowMagZoomROISizeYRBV","B-ES:AMX{Cam:6}ROI1:SizeY_RBV"),
        ("lowMagROISizeXRBV", "B-ES:AMX{Cam:6}ROI2:SizeX_RBV"),
        ("lowMagROISizeYRBV", "B-ES:AMX{Cam:6}ROI2:SizeY_RBV"),
        ("lowMagZoomMaxSizeXRBV","B-ES:AMX{Cam:6}ROI1:MaxSizeX_RBV"),
        ("lowMagZoomMaxSizeYRBV","B-ES:AMX{Cam:6}ROI1:MaxSizeY_RBV"),
        ("lowMagMaxSizeXRBV", "B-ES:AMX{Cam:6}ROI2:MaxSizeX_RBV"),
        ("lowMagMaxSizeYRBV", "B-ES:AMX{Cam:6}ROI2:MaxSizeY_RBV"),
        ("lowMagZoomSizeXRBV","B-ES:AMX{Cam:6}ROI1:ArraySizeX_RBV"),
        ("lowMagZoomSizeYRBV","B-ES:AMX{Cam:6}ROI1:ArraySizeY_RBV"),
        ("lowMagSizeXRBV",    "B-ES:AMX{Cam:6}ROI2:ArraySizeX_RBV"),
        ("lowMagSizeYRBV",    "B-ES:AMX{Cam:6}ROI2:ArraySizeY_RBV"),
        ("lowMagZoomBinXRBV", "B-ES:AMX{Cam:6}ROI1:BinX_RBV"),
        ("lowMagZoomBinYRBV", "B-ES:AMX{Cam:6}ROI1:BinY_RBV"),
        ("lowMagMinXRBV",     "B-ES:AMX{Cam:6}ROI2:MinX_RBV"),
        ("lowMagMinYRBV",     "B-ES:AMX{Cam:6}ROI2:MinY_RBV"),
        ("lowMagBinXRBV",     "B-ES:AMX{Cam:6}ROI2:BinX_RBV"),
        ("lowMagBinYRBV",     "B-ES:AMX{Cam:6}ROI2:BinY_RBV"),
        ("highMagZoomMinXRBV","B-ES:AMX{Cam:7}ROI1:MinX_RBV"),
        ("highMagZoomMinYRBV","B-ES:AMX{Cam:7}ROI1:MinY_RBV"),
        ("highMagMinX",       "B-ES:AMX{Cam:7}ROI2:MinX"),
        ("highMagMinY",       "B-ES:AMX{Cam:7}ROI2:MinY"),
        ("highMagZoomMinX",   "B-ES:AMX{Cam:7}ROI1:MinX"),
        ("highMagZoomMinY",   "B-ES:AMX{Cam:7}ROI1:MinY"),
        ("highMagZoomROISizeXRBV","B-ES:AMX{Cam:7}ROI1:SizeX_RBV"),
        ("highMagZoomROISizeYRBV","B-ES:AMX{Cam:7}ROI1:SizeY_RBV"),
        ("highMagROISizeXRBV","B-ES:AMX{Cam:7}ROI2:SizeX_RBV"),
        ("highMagROISizeYRBV","B-ES:AMX{Cam:7}ROI2:SizeY_RBV"),
        ("highMagZoomMaxSizeXRBV","B-ES:AMX{Cam:7}ROI1:MaxSizeX_RBV"),
        ("highMagZoomMaxSizeYRBV","B-ES:AMX{Cam:7}ROI1:MaxSizeY_RBV"),
        ("highMagMaxSizeXRBV","B-ES:AMX{Cam:7}ROI2:MaxSizeX_RBV"),
        ("highMagMaxSizeYRBV","B-ES:AMX{Cam:7}ROI2:MaxSizeY_RBV"),
        ("highMagZoomSizeXRBV","B-ES:AMX{Cam:7}ROI1:ArraySizeX_RBV"),
        ("highMagZoomSizeYRBV","B-ES:AMX{Cam:7}ROI1:ArraySizeY_RBV"),
        ("highMagSizeXRBV",   "B-ES:AMX{Cam:7}ROI2:ArraySizeX_RBV"),
        ("highMagSizeYRBV",   "B-ES:AMX{Cam:7}ROI2:ArraySizeY_RBV"),
        ("highMagZoomBinXRBV","B-ES:AMX{Cam:7}ROI1:BinX_RBV"),
        ("highMagZoomBinYRBV","B-ES:AMX{Cam:7}ROI1:BinY_RBV"),
        ("highMagMinXRBV",    "B-ES:AMX{Cam:7}ROI2:MinX_RBV"),
        ("highMagMinYRBV",    "B-ES:AMX{Cam:7}ROI2:MinY_RBV"),
        ("highMagBinXRBV",    "B-ES:AMX{Cam:7}ROI2:BinX_RBV"),
        ("highMagBinYRBV",    "B-ES:AMX{Cam:7}ROI2:BinY_RBV"),
        ("detectorNy",        "B-ES:AMX{Det:Eig9M}cam1:ArraySizeY_RBV"),
        ("detectorDescription","B-ES:AMX{Det:Eig9M}cam1:Description_RBV"),
        ("detectorNx",        "B-ES:AMX{Det:Eig9M}cam1:ArraySizeX_RBV"),
        ("detectorROIMode",   "B-ES:AMX{Det:Eig9M}cam1:ROIMode"),
        ("dewarPlatePos",     "B-ES:AMX{CS8}PlatePosition"),
    ]),
}
